export enum HandDirection {
  UP = 'UP',
  DOWN = 'DOWN',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT'
}

type DigitHand = {
  x: number
  y: number
  minuteDirection: HandDirection
  hourDirection: HandDirection
}

export const digitSegments: Record<number, DigitHand[]> = {
  0: [
    // Outer Rectangle
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 3, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 1, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 0, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },

    // Inner Rectangle
    { x: 1, y: 1, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 3, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 2, y: 4, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 1, y: 4, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 1, y: 3, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.UP },
    { x: 1, y: 2, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.UP },

    // Two Middle Clocks (Commented out for now so they don't get coloured in certain themes)
    // { x: 2, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    // { x: 2, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT }
  ],
  1: [
    // The Number 1 Itself
    { x: 2, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.UP },
    { x: 3, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 2, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT }
  ],
  2: [
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 0, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 2, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.DOWN },
    { x: 1, y: 2, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 2, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 3, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 4, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 1, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.DOWN },
    { x: 2, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 3, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 0, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 1, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 0, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.UP },
  ],
  3: [
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 2, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 1, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.UP },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 3, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 1, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 0, y: 4, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 3, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 1, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT }
  ],
  4: [
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.LEFT },
    { x: 3, y: 0, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 0, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 1, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 1, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 2, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 3, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 4, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },

  ],
  5: [
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 1, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 0, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 0, y: 4, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.DOWN },
    { x: 1, y: 2, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 1, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 3, y: 3, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.LEFT },
    { x: 3, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 4, y: 2, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.LEFT },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 3, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 1, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 0, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
  ],
  6: [
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 0, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 0, y: 1, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.UP },
    { x: 1, y: 1, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.UP },
    { x: 0, y: 2, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.UP },
    { x: 1, y: 2, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 2, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 0, y: 3, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.UP },
    { x: 1, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.DOWN },
    { x: 2, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 3, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.UP },
    { x: 0, y: 4, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.UP },
    { x: 1, y: 4, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 2, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.UP },
    { x: 4, y: 4, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.UP },
    { x: 0, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 1, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.UP }
  ],
  7: [
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 5, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.UP },
    { x: 3, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 2, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT }
  ],
  8: [
    // Outer Rectangle
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 3, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 1, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 0, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },

    // Top Inner Square
    { x: 1, y: 1, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 1, y: 2, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 2, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },

    // Bottom Inner Square
    { x: 1, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.DOWN },
    { x: 2, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 3, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 1, y: 4, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 2, y: 4, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 3, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
  ],
  9: [
    { x: 0, y: 0, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 1, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 4, y: 0, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 4, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 4, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 3, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 1, y: 5, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 0, y: 5, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 4, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.DOWN },
    { x: 0, y: 3, minuteDirection: HandDirection.UP, hourDirection: HandDirection.RIGHT },
    { x: 0, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 0, y: 1, minuteDirection: HandDirection.UP, hourDirection: HandDirection.DOWN },
    { x: 1, y: 1, minuteDirection: HandDirection.DOWN, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 1, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 1, y: 2, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.UP },
    { x: 2, y: 2, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 3, y: 2, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
    { x: 1, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 2, y: 3, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 3, y: 3, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.DOWN },
    { x: 1, y: 4, minuteDirection: HandDirection.LEFT, hourDirection: HandDirection.RIGHT },
    { x: 2, y: 4, minuteDirection: HandDirection.RIGHT, hourDirection: HandDirection.LEFT },
    { x: 3, y: 4, minuteDirection: HandDirection.UP, hourDirection: HandDirection.LEFT },
  ]
}