name: Demo Website

on:
  push:
    branches:
      - main

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Store Build
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run test:ci
      - name: Store LCOV Info
        uses: actions/upload-artifact@v4
        with:
          name: line-coverage-info
          path: coverage/lcov.info

  deploy:
    runs-on: ubuntu-latest
    needs: [ unit-tests, build-library, lint ]
    steps:
      - uses: actions/checkout@v4

      - name: Download Production Build
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist